[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.crm.extensions.timelines"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "crm", "timelines", "events"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.extensions.timelines"

[build-options]
observabilityIncluded = true
